# Generated by Django 6.1 on 2026-09-16 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShipPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan_Name', models.CharField(max_length=100)),
                ('Duration', models.PositiveIntegerField()),
                ('Plan_price', models.PositiveIntegerField()),
                ('Plan_Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeatConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.PositiveIntegerField(default=1)),
                ('seats_per_row', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('MemberID', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('joined_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('MemberID__isnull', False)), fields=('MemberID',), name='unique_member_id')],
            },
        ),
        migrations.CreateModel(
            name='Memberships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('amount', models.PositiveIntegerField()),
                ('Payment_Status', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='App.member')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.membershipplans')),
            ],
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='App.member')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='App.seat')),
            ],
        ),
    ]
