# Generated by Django 6.1 on 2026-09-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberships',
            name='Payment_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
