# Generated by Django 6.1 on 2026-09-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShipPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan_Name', models.CharField(max_length=100)),
                ('Duration', models.PositiveIntegerField()),
                ('Plan_price', models.PositiveIntegerField()),
                ('Plan_Status', models.BooleanField(default=True)),
            ],
        ),
    ]
