# Generated by Django 6.1 on 2026-09-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='MemberID',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
