# Generated by Django 6.1 on 2026-09-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_member_memberid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('MemberID__isnull', False)), fields=('MemberID',), name='unique_member_id'),
        ),
    ]
